---
- name: copy scrip to remote host
  template:
    src: templates/restore.sh.j2
    dest: /tmp/restore.sh
    mode: 755

- name: run script to restore
  shell: sudo bash /tmp/restore.sh
  ignore_errors: yes
  register: restore
  
- debug: var=restore.stdout_lines
